### ISSUE TITLE
日期错误反馈

### ISSUE THREAD

**Issue by parchil** [ipuppet/MyDays#1]
设定好日期和标题保存返回，提示invalid date，第一次安装的时候显示正确的，后面修改日期以后就显示无效日期，多次删除重装还是复现，希望您可以查看一下谢谢！
![28284F82-C795-4DB0-B0AA-C0065E154084](https://user-images.githubusercontent.com/70421106/91627271-df85e500-e9e8-11ea-8ce3-6955ba069203.png)
![9C12D74C-D774-4E31-87DE-937A3BEF92C3](https://user-images.githubusercontent.com/70421106/91627273-e14fa880-e9e8-11ea-9907-213a1949a020.png)

**Comment by ipuppet** [comment]
已找到可能出问题的地方，下个版本解决

**Comment by ipuppet** [comment]
不过你这个编辑界面有问题啊
正常情况下应该是这样的：
![image](https://user-images.githubusercontent.com/37722993/91630629-6943ab80-ea05-11ea-9c22-2d19495c2474.png)

**Comment by ipuppet** [comment]
已经更新到1.1.0

更新前请详细阅读更新说明。

(。﹏。*)

**Comment by parchil** [comment]
> 不过你这个编辑界面有问题啊
> 正常情况下应该是这样的：
> ![image](https://user-images.githubusercontent.com/37722993/91630629-6943ab80-ea05-11ea-9c22-2d19495c2474.png)



> 不过你这个编辑界面有问题啊
> 正常情况下应该是这样的：
> ![image](https://user-images.githubusercontent.com/37722993/91630629-6943ab80-ea05-11ea-9c22-2d19495c2474.png)

编辑界面可能跟我是jsbox测试版本有关系吧，新版已经解决了，非常感谢
